/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package reparacion;

import cliente.Cliente;
import dispositivo.Dispositivo;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.table.DefaultTableModel;
import marca.Marca;
import marca.MarcaController;
import modelo.Modelo;
import modelo.ModeloController;
import reparacionTipo.LineaReparacion;
import tipoReparacion.TipoReparacion;
import tipoReparacion.TipoReparacionController;
import utils.Utils;

/**
 *
 * @author sovi8
 */
public class DetalleReparacionDialog extends javax.swing.JDialog {

    private boolean newReparacion;
    private ReparacionController rc = new ReparacionController();
    private Reparacion reparacion;
    private Cliente cliente;
    private DefaultTableModel reparacionesTabla;
    private Marca marcaSelect;
    private Modelo modeloSelect;
    private TipoReparacion tipoReparacionSelect;
    private List<LineaReparacion> tipoReparacionList = new ArrayList<>();
    private BigDecimal importe =  BigDecimal.ZERO;
    
    public DetalleReparacionDialog(java.awt.Frame parent, boolean modal, Cliente cliente, Reparacion reparacion) {
        super(parent, modal);
        initComponents();
        setTitle("REPARACION");
        this.cliente = cliente;
        this.reparacion = reparacion;
        cargarComboBoxMarca();
        cargarComboBoxModelo(1L);
        cargarComboBoxReparacion();
        cargarReparacion(reparacion);
        tablaReparaciones();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        apellidosTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefonoTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        direccionTextField = new javax.swing.JTextField();
        nombreTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        comentariosLabel = new javax.swing.JLabel();
        guardarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentariosTextArea = new javax.swing.JTextArea();
        eliminarButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        garantiaCheckBox = new javax.swing.JCheckBox();
        modeloComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        imeiTextField = new javax.swing.JTextField();
        salidaLabel = new javax.swing.JLabel();
        importeLabel = new javax.swing.JLabel();
        importeTextField = new javax.swing.JTextField();
        estadoComboBox = new javax.swing.JComboBox<>();
        entradaLabel = new javax.swing.JLabel();
        marcaComboBox = new javax.swing.JComboBox<Marca>();
        entradaDate = new com.toedter.calendar.JDateChooser();
        salidaDate = new com.toedter.calendar.JDateChooser();
        reparacionComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        reparacionesJTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        precioTextField = new javax.swing.JTextField();
        addReparacionButton = new javax.swing.JButton();
        delReparacionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 600));

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Teléfono:");

        jLabel6.setText("Dirección:");

        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        comentariosLabel.setText("COMENTARIOS");
        comentariosLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        comentariosTextArea.setColumns(20);
        comentariosTextArea.setRows(5);
        jScrollPane1.setViewportView(comentariosTextArea);

        eliminarButton.setText("Eliminar");

        exitButton.setText("Salir");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        garantiaCheckBox.setText("Garantía");
        garantiaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garantiaCheckBoxActionPerformed(evt);
            }
        });

        modeloComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new Modelo[] {}));

        jLabel8.setText("IMEI:");

        salidaLabel.setText("F.Salida:");

        importeLabel.setText("Importe:");

        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presupuesto", "Pieza Pedida", "En Reparación", "Reparado" }));

        entradaLabel.setText("F.Entrada:");

        marcaComboBox.setEditable(true);
        marcaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new Marca[] {}));

        reparacionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new TipoReparacion[] {}));

        jLabel1.setText("Reparación:");

        jLabel2.setText("Estado:");

        jLabel7.setText("Marca:");

        jLabel9.setText("Modelo:");

        reparacionesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(reparacionesJTable);

        jLabel10.setText("Precio:");

        precioTextField.setText("00");

        addReparacionButton.setText("Añadir");
        addReparacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReparacionButtonActionPerformed(evt);
            }
        });

        delReparacionButton.setText("Eliminar");
        delReparacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delReparacionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(33, 33, 33)
                                        .addComponent(marcaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(precioTextField)
                                            .addComponent(modeloComboBox, 0, 140, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(reparacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addReparacionButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(delReparacionButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imeiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(garantiaCheckBox))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(telefonoTextField)
                                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(direccionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(apellidosTextField))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entradaLabel)
                                    .addComponent(salidaLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(salidaDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(entradaDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(375, 375, 375)
                                .addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(importeLabel))
                                    .addComponent(importeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel2)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(comentariosLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(apellidosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaLabel)
                            .addComponent(entradaDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salidaLabel)
                            .addComponent(salidaDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(modeloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(imeiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(garantiaCheckBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(reparacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(precioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addReparacionButton)
                    .addComponent(delReparacionButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(importeLabel)
                        .addGap(3, 3, 3)
                        .addComponent(importeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(comentariosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(guardarButton)
                    .addComponent(eliminarButton))
                .addContainerGap())
        );

        entradaDate.setDate(new Date());
        salidaDate.setDate(new Date());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void garantiaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garantiaCheckBoxActionPerformed
      
    }//GEN-LAST:event_garantiaCheckBoxActionPerformed
  
    // Cargar datos de la reparación
    public void cargarReparacion(Reparacion reparacion){
        
        // Si es una nueva reparación, solo cargo datos del cliente
        if(reparacion == null){
            System.out.println("NUEVA REPARACION");
            newReparacion = true;
            this.reparacion = new Reparacion();
            this.reparacion.setDispositivo(new Dispositivo());
            this.reparacion.getDispositivo().setModelo(modeloSelect);
            nombreTextField.setText(cliente.getNombre());
            apellidosTextField.setText(cliente.getApellidos());
            telefonoTextField.setText(cliente.getTelefono());
            direccionTextField.setText(cliente.getDireccion());
        }
        // Si la reparación ya existe, cargo datos del cliente y de la reparación
        else{
            System.out.println("REPARACION EXISTENTE");
            newReparacion = false;
            nombreTextField.setText(cliente.getNombre());
            apellidosTextField.setText(cliente.getApellidos());
            telefonoTextField.setText(cliente.getTelefono());
            direccionTextField.setText(cliente.getDireccion());
            garantiaCheckBox.setSelected(reparacion.isGarantia());
            entradaDate.setDate(Utils.toDate(reparacion.getFechaEntrada()));
            salidaDate.setDate(Utils.toDate(reparacion.getFechaSalida()));
            importeTextField.setText(reparacion.getImporte().toString());
            imeiTextField.setText(reparacion.getDispositivo().getImei());
        }  
    }
    
    // Cargar combobox marca
    public void cargarComboBoxMarca(){       
        marcaComboBox.removeAllItems();
        
        List<Marca> marcas = MarcaController.llenarComboBoxMarca();      
        for(Marca m : marcas){
            marcaComboBox.addItem(m);
        }
        marcaComboBox.setSelectedItem(marcas.getFirst()); // Asigna la primera marca por defecto
        // Listener
        marcaComboBox.addActionListener(e -> {
            // Asigno la marca seleccionada
            marcaSelect = (Marca) marcaComboBox.getSelectedItem();           
            // Cargo combobox de modelos según la marca seleccionada
            cargarComboBoxModelo(marcaSelect.getId());
        });
    }
    
    // Cargar combobox modelo
    public void cargarComboBoxModelo(Long marcaId){
        modeloComboBox.removeAllItems();
        List<Modelo> modelos = ModeloController.getModelos();
        for(Modelo m : modelos){
            if(marcaId.equals(m.getMarca().getId())){
                modeloComboBox.addItem(m);
            }
            modeloComboBox.setSelectedItem(modelos.getFirst()); // Asigna el primer modelo por defecto
        }  
        // Listener
        modeloComboBox.addActionListener(e -> {
            // Asigno el modelo seleccionado
            modeloSelect = (Modelo) modeloComboBox.getSelectedItem();
        });
       
    }    
    
    // Cargar reparacionComboBox
    public void cargarComboBoxReparacion(){
        reparacionComboBox.removeAllItems();
        List<TipoReparacion> tipoReparacionList = TipoReparacionController.getReparacionesList();
        for(TipoReparacion t : tipoReparacionList){
            reparacionComboBox.addItem(t);
        }
        // Asigna el primer tipo de reparación por defecto
        if (!tipoReparacionList.isEmpty()) {
            reparacionComboBox.setSelectedIndex(0);
            tipoReparacionSelect = (TipoReparacion) reparacionComboBox.getSelectedItem();
        }
        // Listener
        reparacionComboBox.addActionListener(e -> {
            tipoReparacionSelect = (TipoReparacion) reparacionComboBox.getSelectedItem();
        });
    }
    
    // Tabla que contiene TipoReparacion y precio
    public void tablaReparaciones() {
        reparacionesTabla = new DefaultTableModel(
            new Object[]{"Tipo de reparación", "Precio"},
            0
        );

        reparacionesJTable.setModel(reparacionesTabla);
    }
    
    // Comprobación de campos
    public void checkField(){
        // Compruebo longitud del imei
        if(imeiTextField.getText().length() < 15 || imeiTextField.getText().length() > 15){
            JOptionPane.showMessageDialog(null, "El IMEI no es válido.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Compruebo el importe
         if (importe == null) {
            JOptionPane.showMessageDialog(null, "Revise el importe", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
         if(nombreTextField.getText().trim().isEmpty()){
              JOptionPane.showMessageDialog(null, "Revise el nombre del cliente", "ERROR", JOptionPane.ERROR_MESSAGE);
              return;
         }
        if(telefonoTextField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Revise el número de teléfono del cliente", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(tipoReparacionList.size() < 1){
            JOptionPane.showMessageDialog(null, "Debe añadir mínimo un tipo de reparación", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed

        checkField();
        
        // Obtengo datos del cliente
        cliente.setNombre(nombreTextField.toString());
        cliente.setApellidos(apellidosTextField.toString());
        cliente.setTelefono(telefonoTextField.toString());
        cliente.setDireccion(direccionTextField.toString());
        
        // Obtengo fecha entrada/salida
        reparacion.setFechaEntrada(Utils.checkFecha(entradaDate));
        reparacion.setFechaSalida(Utils.checkFecha(salidaDate));
        
        // Obtengo datos del dispositivo
        reparacion.getDispositivo().setCliente(cliente);
        reparacion.getDispositivo().setModelo(modeloSelect);
        reparacion.getDispositivo().setImei(imeiTextField.getText().trim());
        reparacion.setGarantia(garantiaCheckBox.isSelected());
        
        // Obtengo datos de la reparación
        reparacion.setReparacionTipo(tipoReparacionList); // Lista de reparaciones
        reparacion.setImporte(importe); // Importe total
        reparacion.setEstado(estadoComboBox.getSelectedItem().toString());// Estado  
        reparacion.setComentarios(comentariosTextArea.getText()); // Comentarios

        // Si es una nueva reparación
        if (rc.addReparacion(reparacion)) {
            System.out.println("6");
            JOptionPane.showMessageDialog(
                this,
                "La reparación se ha guardado correctamente",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        // Si es una reparación existente
        else if(!newReparacion){
            //reparacion.getDispositivo().getModelo().setMarca(marcaSelect);
            
        }
        System.out.println("LLAMANDO A DAO");
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    // Eliminar tipo de reparacion de la lista y de la tabla
    private void delReparacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delReparacionButtonActionPerformed
        
        int fila = reparacionesJTable.getSelectedRow();
        
        if(fila < 0) return;
        
        tipoReparacionList.remove(fila);
        reparacionesTabla.removeRow(fila);   
        
        // Actualizo el importe
        actualizarImporte();
    }//GEN-LAST:event_delReparacionButtonActionPerformed

    // Botón añadir reparación a la lista y a la tabla
    private void addReparacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReparacionButtonActionPerformed
          // Agrega la reparacion a la tabla
            reparacionesTabla.addRow(new Object[]{
            tipoReparacionSelect.getNombre(),
            precioTextField.getText()
        });
            // Agrega el tipo de reparacion a la lista de reparación
            LineaReparacion rt = new LineaReparacion();
            rt.setTipoReparacion(tipoReparacionSelect);
            rt.setPrecio(Utils.stringToBigDecimal(precioTextField.getText()));
            tipoReparacionList.add(rt);
            
            // Actualizo el importe
            actualizarImporte();
            
    }//GEN-LAST:event_addReparacionButtonActionPerformed

    private void actualizarImporte() {
        importe = BigDecimal.ZERO;

        for (LineaReparacion rt : tipoReparacionList) {
            importe = importe.add(rt.getPrecio());
        }

        importeTextField.setText(importe.toString());
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addReparacionButton;
    private javax.swing.JTextField apellidosTextField;
    private javax.swing.JLabel comentariosLabel;
    private javax.swing.JTextArea comentariosTextArea;
    private javax.swing.JButton delReparacionButton;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JButton eliminarButton;
    private com.toedter.calendar.JDateChooser entradaDate;
    private javax.swing.JLabel entradaLabel;
    private javax.swing.JComboBox<String> estadoComboBox;
    private javax.swing.JButton exitButton;
    private javax.swing.JCheckBox garantiaCheckBox;
    private javax.swing.JButton guardarButton;
    private javax.swing.JTextField imeiTextField;
    private javax.swing.JLabel importeLabel;
    private javax.swing.JTextField importeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<Marca> marcaComboBox;
    private javax.swing.JComboBox<Modelo> modeloComboBox;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField precioTextField;
    private javax.swing.JComboBox<TipoReparacion> reparacionComboBox;
    private javax.swing.JTable reparacionesJTable;
    private com.toedter.calendar.JDateChooser salidaDate;
    private javax.swing.JLabel salidaLabel;
    private javax.swing.JTextField telefonoTextField;
    // End of variables declaration//GEN-END:variables
}
