/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package reparacion;

import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sovi8
 */
public class ReparacionesTable extends javax.swing.JPanel {

    private JTable tablaReparaciones = new JTable();
    private DefaultTableModel reparacionesTable = new DefaultTableModel();
    
    public ReparacionesTable(List<Reparacion> reparacionesList) {
        initComponents();
         String[] columnas = {"ENTRADA", "SALIDA", "CLIENTE", "DISPOSITIVO", "ESTADO", "IMPORTE"};
        reparacionesTable = new DefaultTableModel(columnas, 0){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        System.out.println("REPARACIONES TABLE");
        tablaReparaciones = new JTable(reparacionesTable);
        JScrollPane scrollPane = new JScrollPane(tablaReparaciones);

        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        add(scrollPane);
        setReparaciones(reparacionesList);
    }
    
     public void setReparaciones(List<Reparacion> reparacionesList){
        reparacionesTable.setRowCount(0);
        for (Reparacion r : reparacionesList) {
            Object[] fila = {
                r.getFechaEntrada(),
                r.getFechaSalida(),
                r.getDispositivo().getCliente().getNombre().toUpperCase() + " " + r.getDispositivo().getCliente().getApellidos(),
                r.getDispositivo().getModelo().getNombre().toUpperCase(),
                r.getEstado().toUpperCase(),
                r.getImporte()
            };
            reparacionesTable.addRow(fila);
        }
   }
   
   public JTable getTablaReparaciones(){
       return tablaReparaciones;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
